kafka {
  groupId = "helsemelding.outbound-processing-service"
  bootstrapServers = "${KAFKA_BROKERS:-http://localhost:9092}"
  securityProtocol = "SSL"
  keystoreType = "PKCS12"
  keystoreLocation = "${KAFKA_KEYSTORE_PATH:-}"
  keystorePassword = "${KAFKA_CREDSTORE_PASSWORD:-}"
  truststoreType = "JKS"
  truststoreLocation = "${KAFKA_TRUSTSTORE_PATH:-}"
  truststorePassword = "${KAFKA_CREDSTORE_PASSWORD:-}"
  topics {
    dialogMessageOutJson = "helsemelding.dialog.out.json"
    dialogMessageOutXml = "helsemelding.dialog.out.xml"
    errorMessage = "helsemelding.dialog.out.error"
  }
}

httpClient {
  connectionTimeout = "${HTTP_CLIENT_TIMEOUT_IN_SECONDS:-3}s"
}

httpTokenClient {
  // should be < httpClient timeout
  connectionTimeout = "${TOKEN_CLIENT_TIMEOUT_IN_SECONDS:-2}s"
}

pdl {
  graphqlUrl = "${PDL_GRAPHQL_URL:-https://pdl-api.dev-fss-pub.nais.io/graphql}"
  processingNumber = "${PDL_PROCESSING_NUMBER:-B1047}"
  scope = "${PDL_SCOPE:-api://dev-fss.pdl.pdl-api/.default}"
}

providerRegistry {
  baseUrl = "${PROVIDER_REGISTRY_BASE_URL:-http://isdialogmelding.teamsykefravr}"
  scope = "${PROVIDER_REGISTRY_SCOPE:-api://dev-gcp.teamsykefravr.isdialogmelding/.default}"
}

server {
  port = 8080
  // time before shutdown is initiated
  preWait = "5s"
}

azureAuth {
  azureGrantType = "client_credentials"
  azureTokenEndpoint = "${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT:-http://localhost:3344/AZURE_AD/token}"
  azureAppClientId = "${AZURE_APP_CLIENT_ID:-test-aud}"
  azureAppClientSecret = "${AZURE_APP_CLIENT_SECRET:-test-secret}"
}
