kafkaStreamsSettings {
  applicationId = "helsemelding.outbound-processing-service"
  bootstrapServers = "${KAFKA_BROKERS:-http://localhost:9092}"
  securityProtocol = "SSL"
  keystoreType = "PKCS12"
  keystoreLocation = "${KAFKA_KEYSTORE_PATH:-}"
  keystorePassword = "${KAFKA_CREDSTORE_PASSWORD:-}"
  truststoreType = "JKS"
  truststoreLocation = "${KAFKA_TRUSTSTORE_PATH:-}"
  truststorePassword = "${KAFKA_CREDSTORE_PASSWORD:-}"
  defaultKeySerde = "org.apache.kafka.common.serialization.Serdes$StringSerde"
  defaultValueSerde = "org.apache.kafka.common.serialization.Serdes$StringSerde"
  topics {
    dialogMessageIn = "helsemelding.dialog.out.json"
    dialogMessageOut = "helsemelding.dialog.out.xml"
    dialogMessageError = "helsemelding.dialog.error"
  }
}

server {
  port = 8080
  // time before shutdown is initiated
  preWait = "5s"
}